### ISSUE TITLE
"JWT must be provided" if token is malformed or empty

### ISSUE THREAD

**Issue by Bargamut** [fatukunda/user-registration-api#3]
Hi! )

In case empty or malformed token we have an error like
`JWT must be provided` or `JWT malformed`.

https://github.com/fatukunda/user-registration-api/blob/cd553f4b32a153f3ec0c07f6bf2e97253a46bce7/src/middleware/auth.js#L6

Is it better if we move this string into `try { }` like this?
```js
// other code of auth middleware

try {
  const data = jwt.verify(token, process.env.JWT_KEY);

  // other code
} catch {
  // etc
}
```

In this case we can see `Not authorized to access this resource` instead of crash in console and user can relogin now.

**Comment by fatukunda** [comment]
@Bargamut Yeah sure we can do that. Thanks for pointing this out.
