### ISSUE TITLE
findByCredentials Errors

### ISSUE THREAD

**Issue by puc-covelli** [fatukunda/user-registration-api#8]
When I pass in an incorrect password the findByCredentials never seems to throw the error andn I always just get an empty JSON packet instead of the "Invalid login credentials" error message

**Comment by dangvm2** [comment]
Because ErrorConstructor's parameter is: Error new (message?: string)

So you can fix it follow this [commit](https://github.com/dangvm2/user-registration-api/commit/19a550fe5c4680a1fe366e0c5a329ec4588c0239)
